version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/vector-db
    volumes:
      - .:/app  # Mount the current directory into /app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath=/dev/null --logappend
    volumes:
      - mongodb_data:/data/db
    # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data: 